
spring:
    application:
        name: aluno-consumer
    h2:
        console:
            enabled: true
            path: /h2
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:testdb
        username: sa
        password: 
    rabbitmq:
        address: amqp://guest@127.0.0.1:15672/
        host: localhost
        port: 5672
        username: guest
        password: guest
        queue: aluno-sent
        exchange: alunos
    
server:
    port: 8084
eureka:
    instance:
        hostname: localhost
        port: 9000
    client:
        serviceUrl: 
            defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka