
spring:
    application:
        name: consumer-service
    rabbitmq:
        address: amqp://guest@127.0.0.1:15672/
        host: localhost
        port: 5672
        username: guest
        password: guest
        queue: professor-sent
        exchange: professores

    mail:
        host: gmail.com
        port: 587
        username: bruno.silva123854@gmail.com
        password: #*************  mudar
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

server:
    port: 8082
    #port: 8084
eureka:
    instance:
        hostname: localhost
        port: 9001
    client:
        serviceUrl: 
            registerWithEureka: false
            fetchRegistry: false
            defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka